account/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from account import views
from account.forms import MyAuthenticationForm, MyPasswordChangeForm

app_name = 'account'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='account/login.html',
            authentication_form=MyAuthenticationForm
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'register/',
        views.register,
        name='register'
    ),
    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('account:password_change_done'),
            template_name='account/password_change.html',
            form_class=MyPasswordChangeForm
            ),
        name='password_change'
    ),
    path(
        'password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'user/<str:username>/',
        views.user_profile,
        name='user_profile'
    ),
    path(
        'edit/',
        views.user_edit,
        name='user_edit'
    ),
    path(
        'user/follow/<str:username>/',
        views.user_follow,
        name='user_follow'
    ),
    path(
        'user/unfollow/<str:username>/',
        views.user_unfollow,
        name='user_unfollow'
    ),
]

post/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from post import views

app_name = 'post'
urlpatterns = [
    path(
        'post/upload/',
        views.post_upload,
        name='post_upload'
    ),
    path(
        '',
        views.post_list,
        name='post_list'
    ),
    path(
        'post/detail/<int:id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'post/like/',
        views.post_like,
        name='post_like'
    ),
    path(
        'post/',
        views.get_post,
        name='get_post'
    ),
    path(
        'post/comment',
        views.comment,
        name='comment'
    )
]

weshare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from .settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse

from sorl.thumbnail import ImageField


class Post(models.Model):
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    image = ImageField(upload_to='images/%Y/%m/%d/')
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='posts_created'
    )
    user_like = models.ManyToManyField(
        to=User,
        related_name='posts_liked',
        blank=True
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Post {} by {}'.format(self.body, self.user.first_name)
    

class Comment(models.Model):
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='comments_created'
    )
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.user.first_name)
    

post/forms.py
from django import forms
from post.models import Post, Comment

class PostForm(forms.ModelForm):
    image = forms.ImageField(
        label="圖片"
    )
    body = forms.CharField(
        label="內容",
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Post
        fields = ('body', 'image')

class CommentForm(forms.ModelForm):
    body = forms.CharField(
        label="評論",
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Comment
        fields = ('body',)

post/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from post.forms import PostForm, CommentForm
from post.models import Post, Comment


# def get_recommend_users(user):
#     all = set()
#     followings = user.following.all()
#     for following in followings:
#         following_followings = following.following.all()
#         for following_following in following_followings:
#             all.add(following_following)
#     if len(all) < 5:
#         pass
#     return 'XD'

@login_required
def post_upload(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            return render(
                request,
                'post/post_upload_done.html'
            )
    else:
        form = PostForm()
    return render(
        request,
        'post/post_upload.html',
        {
            'form': form
        }
    )

@login_required
def post_list(request):
    # recommend_users = get_recommend_users(request.user)
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'post/post_list.html',
        {
            'posts': posts
        }
    )

@login_required
def post_detail(request, id):
    post = Post.objects.get(id=id)
    return render(
        request,
        'post/post_detail.html',
        {
            'post': post
        }
    )

@login_required
def post_like(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        post = Post.objects.get(id=id)
        if request.user not in post.user_like.all():
            post.user_like.add(request.user)
            data = {
                'like_count': post.user_like.count(),
                'is_like': True
            }
        else:
            post.user_like.remove(request.user)
            data = {
                'like_count': post.user_like.count(),
                'is_like': False
            }
        return JsonResponse(data)

@login_required
def get_post(request):
    id = request.GET.get('id')
    post = Post.objects.get(id=id)
    comments = post.comments.all()
    comment_users = [comment.user for comment in comments]
    comment_user_avatars = [comment_user.get_avatar() for comment_user in comment_users]
    comment_user_names = [comment_user.first_name for comment_user in comment_users]
    comment_user_profiles = [reverse('account:user_profile', kwargs={'username': comment_user.username}) for comment_user in comment_users]
    comment_contents = [comment.body for comment in comments]
    data = {
        'first_name': post.user.first_name,
        'avatar': post.user.get_avatar(),
        'image_url': post.image.url,
        'post_body': post.body,
        'like_count': post.user_like.count(),
        'comment_user_avatars': comment_user_avatars,
        'comment_user_names': comment_user_names,
        'comment_user_profiles': comment_user_profiles,
        'comments': comment_contents
    }
    if request.user in post.user_like.all():
        data.update({'is_like': True})
    else:
        data.update({'is_like': False})
    return JsonResponse(data)

@login_required
def comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            id = request.POST.get('id')
            post = Post.objects.get(id=id)
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            data = {
                'comment_user_avatar': comment.user.get_avatar(),
                'comment_user_name': comment.user.first_name,
                'comment_user_profile': reverse('account:user_profile', kwargs={'username': comment.user.username}),
                'comments': comment.body
            }
            return JsonResponse(data)
        return JsonResponse({'message': 'Error.'})
        

post/templates/post/_cards.html
{% load static %}
{% load thumbnail %}

{% for post in posts %}
  <div class="card">
    <div class="card-header d-flex flex-wrap align-items-center">
      <span>
        <a href="{% url 'account:user_profile' post.user.username %}">
          <img src="{{ post.user.get_avatar }}" class="avatar-40">
          {{ post.user.first_name }}
        </a>
      </span>
    </div>
    {% thumbnail post.image "800x800" crop="center" as im %}
      <img class="card-img-top" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-body border-bottom">
      <a href="#" class="user-like" data-id="{{ post.id }}">
        {{ post.user_like.count }} 個喜歡 
        {% if request.user in post.user_like.all %}
          <img class="card-icon like-icon" src="{% static 'img/like.png' %}">
        {% else %}
          <img class="card-icon like-icon" src="{% static 'img/unlike.png' %}">
        {% endif %} 
      </a>
      <a href="{% url 'post:post_detail' post.id %}" class="">
        <img class="card-icon" src="{% static 'img/comment.png' %}">
      </a>
      <div class="card-text-1">
        {{ post.body|linebreaks|slice:"50" }}
        {% if post.body|length > 50 %}
          <a href="#">...更多</a>
        {% endif %}
      </div>
      <div class="card-text-2" style="display: none;">{{ post.body|linebreaks }}</div>
      <div class="comment-block">
        {% for comment in post.comments.all|slice:":2" %}
          <div>
            <a href="{% url 'account:user_profile' comment.user.username %}">
              <b>{{ comment.user.first_name }} </b>
            </a>
            {{ comment.body }}
            <br>
          </div>
        {% endfor %}
      </div>
    </div>
    <form class="comment-form" action="" method="POST" data-id="{{ post.id }}">
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <textarea name="body" class="form-control" placeholder="留言"></textarea>
        </div>
        <div class="col-auto">
          <input type="submit" value="發布" class="btn btn-primary float-right">
        </div>
      </div>
    </form>
  </div>
{% endfor %}

<div>
  <ul>
    {% if posts.has_previous %}
      <li>
        <a href="?page={{ posts.previous_page_number }}"> &larr; Newer posts</a>
      </li>
    {% endif %}
    {% if posts.has_next %}
      <li>
        <a href="?page={{ posts.next_page_number }}">Older posts &rarr;</a>
      </li>
    {% endif %}    
  </ul>
</div>

post/templates/post/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Post | {% endblock %}

{% block content %}
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-7">
          <div class="modal-img-host d-flex flex-wrap align-items-center">
            <img class="modal-img" src="{{ post.image.url }}">
          </div>
        </div>
        <div class="col-md-5">
          <div class="modal-header d-flex flex-wrap align-items-center">
            <span class="modal-user">
              <img class="modal-avatar avatar-40" src="{{ post.user.get_avatar }}">
              {{ post.user.first_name }}  
            </span>
            <span>
              <a href="#" class="user-like" data-id="{{ post.id }}">
                {{ post.user_like.count }} 個喜歡
                {% if request.user in post.user_like.all %}
                  <img class="card-icon like-icon" src="{% static 'img/like.png' %}">
                {% else %}
                  <img class="card-icon like-icon" src="{% static 'img/unlike.png' %}">
                {% endif %}
              </a>
            </span>
          </div>
          <div class="modal-body  border-bottom">
            {{ post.body|linebreaks }}
            <div class="comment-block">
              {% for comment in post.comments.all %}
                <div class="row">
                  <div class="col-sm-auto">
                    <a href="{% url 'account:user_profile' comment.user.username %}">
                      <img src="{{ comment.user.get_avatar }}" class="avatar-30">
                    </a>
                  </div>
                  <div class="col-sm">
                    <a href="{% url 'account:user_profile' comment.user.username %}">
                      <b>{{ comment.user.first_name }}</b>
                    </a>
                    {{ comment.body }}
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          <form class="comment-form" action="" method="POST" data-id="{{ post.id }}">
            {% csrf_token %}
            <div class="row">
              <div class="col">
                <textarea name="body" class="form-control" placeholder="留言"></textarea>
              </div>
              <div class="col-auto">
                <input type="submit" value="發布" class="btn btn-primary float-right">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
{{ block.super }}
  <script>
    // 喜歡按鈕切換
    $('.user-like').click(function(e) {
      e.preventDefault()
      item = $(this)
      id = item.attr('data-id')
      data = {'id': id, 'csrfmiddlewaretoken': '{{ csrf_token }}'}
      jQuery.post(
        '{% url "post:post_like" %}',
        data,
        function(res) {
          item.text(res['like_count'] + ' 個喜歡 ')
          if(res['is_like']) {
            item.append('<img class="card-icon" src="{% static "img/like.png" %}">')
          }
          else {
            item.append('<img class="card-icon" src="{% static "img/unlike.png" %}">')
          }
        }
      )
    })

    // 發表評論
    $('.comment-form').on('submit', function(e) {
      e.preventDefault()
      item = $(this)
      id = item.attr('data-id')
      body = item.find('textarea').val()
      data = {'id': id, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'body': body}
      if(body != '') {
        jQuery.post(
          '{% url "post:comment" %}',
          data,
          function(res) {
            $('.comment-block').append(
              '<div class="row">' +
                  '<div class="col-sm-auto">' +
                    '<a href="' + res['comment_user_profile'] + '">' +
                      '<img src="' + res['comment_user_avatar'] + '" class="avatar-30">' +
                    '</a>' +
                  '</div>' +
                  '<div class="col-sm">' +
                    '<a href="' + res['comment_user_profile'] + '">' +
                      '<b>' + res['comment_user_name'] + ' </b>' +
                    '</a>' +
                    res['comments'] +
                  '</div>' +
                '</div>'
            )
            $('.comment-form textarea').val('')
            $('.modal-body').animate({scrollTop:$('.modal-body')[0].scrollHeight},'1000');
          }
        )
      }
    })
  </script>
{% endblock %}

post/templates/post/post_list.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
  {% include 'post/_cards.html' %}
{% endblock %}

{% block scripts %}
{% load static %}
{{ block.super }}
	<script>
    $('.card-text-1 a').click(function(e) {
      e.preventDefault()
      $('.card-text-1').hide()
      $('.card-text-2').show()
    })

    $('.user-like').click(function(e) {
      e.preventDefault()
      item = $(this)
      id = item.attr('data-id')
      data = {'id': id, 'csrfmiddlewaretoken': '{{ csrf_token }}'}
      jQuery.post(
        '{% url "post:post_like" %}',
        data,
        function(res) {
          item.text(res['like_count'] + ' 個喜歡 ')
          if(res['is_like']) {
            item.append('<img class="card-icon like-icon" src="{% static "img/like.png" %}">')
          }
          else {
            item.append('<img class="card-icon like-icon" src="{% static "img/unlike.png" %}">')
          }
        }
      )
    })

    // 發表評論
    $('.comment-form').on('submit', function(e) {
      e.preventDefault()
      item = $(this)
      id = item.attr('data-id')
      body = item.find('textarea').val()
      data = {'id': id, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'body': body}
      if(body != '') {
        jQuery.post(
          '{% url "post:comment" %}',
          data,
          function(res) {
            item.parent().find('.comment-block').append(
              '<div>' +
                '<a href="' + res['comment_user_profile'] + '">' +
                  '<b>' + res['comment_user_name'] + ' </b>' +
                '</a>' +
                res['comments'] +
              '</div>'
            )
            item.find('textarea').val('')
          }
        )
      }
    })
	</script>
{% endblock %}

post/templates/post/post_upload.html
{% extends "base.html" %}

{% block title %}Post | {% endblock %}

{% block content %}
  <div class="card">
    <div class="card-header">
      <h3>發表</h3>
    </div>
    <div class="card-body">
      <form action="." method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <p>
          <a href="{% url 'post:post_list'%}" class="btn btn-secondary">取消</a>
          <input type="submit" class="btn btn-success" value="上傳">
        </p>
      </form>
    </div>
  </div>
{% endblock %}

post/templates/post/post_upload_done.html
{% extends "base.html" %}

{% block title %}Post | {% endblock %}

{% block content %}
  <div class="card">
    <div class="card-header">
      <h3>上傳成功</h3>
    </div>
    <div class="card-body">
      <p>
        您的發表已完成，回個人檔案
        <a href="{% url 'account:user_profile' request.user.username %}">查看</a>
      </p>
    </div>
  </div>
{% endblock %}