account/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from account import views
from account.forms import MyAuthenticationForm, MyPasswordChangeForm

app_name = 'account'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='account/login.html',
            authentication_form=MyAuthenticationForm
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'register/',
        views.register,
        name='register'
    ),
    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('account:password_change_done'),
            template_name='account/password_change.html',
            form_class=MyPasswordChangeForm
            ),
        name='password_change'
    ),
    path(
        'password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'user/<str:username>/',
        views.user_profile,
        name='user_profile'
    ),
    path(
        'edit/',
        views.user_edit,
        name='user_edit'
    ),
    path(
        'user/follow/<str:username>/',
        views.user_follow,
        name='user_follow'
    ),
    path(
        'user/unfollow/<str:username>/',
        views.user_unfollow,
        name='user_unfollow'
    ),
]

post/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from post import views

app_name = 'post'
urlpatterns = [
    path(
        'post/upload/',
        views.post_upload,
        name='post_upload'
    ),
    path(
        '',
        views.post_list,
        name='post_list'
    ),
    path(
        'post/detail/<int:id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'post/like/',
        views.post_like,
        name='post_like'
    ),
    path(
        'post/',
        views.get_post,
        name='get_post'
    ),
    path(
        'post/comment',
        views.comment,
        name='comment'
    )
]

weshare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from .settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}WeShare</title>
  <link rel=icon href="{% static 'img/favicon-16x16.png' %}" sizes="any" type="image/png">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/grid-gallery.css' %}">
</head>
<body>
  <nav class="navbar fixed-top navbar-expand navbar-light bg-light border-bottom border-gray">
    <div class="container">
      <a class="navbar-brand" href="{% url 'post:post_list' %}">
        <img src="{% static 'img/LOGO.png' %}" width="150px">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto"> 
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'post:post_list' %}" class="nav-link">
                <img src="{% static 'img/home.png' %}" class="nav-icon">
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'post:post_upload' %}" class="nav-link">
                <img src="{% static 'img/post.png' %}" class="nav-icon">
              </a>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <img src="{% static 'img/setting.png' %}" class="nav-icon">
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'account:user_profile' request.user.username %}" class="dropdown-item">個人頁面</a>
                </li>
                <li>
                  <a href="{% url 'account:user_edit'%}" class="dropdown-item">編輯檔案</a>
                </li>
                <li>
                  <a href="{% url 'account:password_change' %}" class="dropdown-item">修改密碼</a>
                </li>
                <li>
                  <a href="{% url 'account:logout' %}" class="dropdown-item">登出</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:user_profile' request.user.username %}" class="nav-link">
                <img src="{{ request.user.get_avatar }}" class="avatar-30">
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'account:login' %}" class="nav-link">登入</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  <section class="page-section">
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </section>

  {% block scripts %}
    <script src="{% static 'vendor/jquery/jquery-3.5.1.min.js' %}"></script>  
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
  {% endblock %}
</body>
</html>